learn/devops/devops/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.urls import path,include
from hello import views

# 用户输入是 http://ip:80081/hello
# 从hello app中定一个叫views.py模块index函数来处理hello这个用户请求
# from hello import views
app_name = 'hello'
urlpatterns = [
    # path('admin/', admin.site.urls),
    # 如果hello，总入口直接指向具体app等具体方法，一旦app过多，路由过多，注入口将不堪重负，所以要分而治之
    # path('hello/', views.index),
    # 当你访问hello时，我不知道具体方法，而是告诉你去hello app中的urls.py
    path('hello/', include('hello.urls')),
    # 关键字匹配(最优雅) (?<参数>参数类型) 视图中直接通过参数名获取值(最常用)
    # re_path('(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/', views.index, name='index'),
]

learn/devops/hello/urls.py
from django.urls import path,re_path
from . import views,views1,views2,views3
from hello.views2 import IndexView,IndexView2
from hello import views4

app_name = 'hello'
urlpatterns = [

    # html css Jquery学习
    path('html/', views4.HtmlView.as_view(), name='html'),
    path('form/', views4.FormView.as_view(), name='form'),
    path('modelform/', views4.UserModelFormView.as_view(), name='form'),


    path('hello/', views.index, name='index'),
    path('list/', views.list, name = 'list'),

    # 简易用户管理系统
    path('useradd/', views1.useradd, name="useradd"),
    path('userlist/', views1.userlist, name="userlist"),
    re_path('modify/(?P<pk>[0-9]+)?/', views1.modify, name="modify"),
    re_path('userdel/(?P<pk>[0-9]+)?/', views1.userdel, name="userdel"),


    # FBV 实现增删改查
    # path('index/', views2.index, name='index'),

    # 通用视图
    # as_view 源码中的dispatch函数将用户请求method映射成对应的function
    path('index/', views2.IndexView.as_view()),

    # View
    path('index1/', views2.IndexView1.as_view()),
    # TemplateView
    path('index2/', views2.IndexView2.as_view(), name='index2'),
    re_path('index2/(?P<pk>[0-9]+)?/', views2.IndexView2.as_view(), name='index2'),

    # ListView--查询数据表所有数据
    path('index3/', views2.IndexView3.as_view(), name='index3'),

    # DetailView--查询数据表的某一条数据
    re_path('index4/(?P<pk>[0-9]+)?/', views2.IndexView4.as_view(), name='index4'),

    # CreateView--创建数据
    path('index5/',views2.IndexView5.as_view(), name='index5'),

    # UpdateView--更新数据
    re_path('index6/(?P<pk>[0-9]+)?/', views2.IndexView6.as_view(), name='index6'),

    # DeleteView--删除数据
    re_path('index7/(?P<pk>[0-9]+)?/', views2.IndexView7.as_view(), name='index7'),
    # (?P<pk>[0-9]+)? -> 这个是ID的写法，用户后端出入到前端的ID

    # CBV简易用户管理系统版本一：利用编辑通用视图处理表单
    path('useradd1/', views3.UserAddView.as_view(), name='useradd1'),
    path('userlist1/', views3.UserListView.as_view(), name='userlist1'),
    re_path('detail/(?P<pk>[0-9]+)?/', views3.UserDetailView.as_view(), name='detail'),
    re_path('modify1/(?P<pk>[0-9]+)?/', views3.UserUpdateView.as_view(), name='modify1'),
    re_path('userdel1/(?P<pk>[0-9]+)?/', views3.UserDeleteView.as_view(), name='userdel1'),
]

learn/devops/books/models.py
from django.db import models

# 出版商表结构
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)

    def __str__(self):
        return self.name

# 作者信息表结构
class Author(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()

    def __str__(self):
        return self.name

# 书的表结构
class Book(models.Model):
    title = models.CharField(max_length=100, help_text="书名")
    # 作者和书是多对多的关系
    authors = models.ManyToManyField(Author, verbose_name="作者", help_text="作者")
    # 一本书只能被一家出版商出版，出版商可以出版多本书
    publisher = models.ForeignKey(Publisher, verbose_name="出版社", help_text="出版社", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

"""
-- 带关联字段带的表称为主表(book),不带的称为从表(authors)
-- 正向添加 && 正向查找
b = Book.objects.get(pk=1) # b 是书
a = Author.objects.get(id=3) # a 是作者


1. 查询主表的一条记录
b = Book.objects.get(pk=1)

2. 查询从表一条需要添加的对象
a = Author.objects.get(id=1)

3. 将这个对象添加/追加给这个主表记录
b.authors.add(a)

4. 查询从表一串对象
a__list = Author.objects.filter(id__gt=2) 

5. 有两种方式将这个从表的列表的数据，给主表记录
5.1 追加
b.authors.add(*a_list)
5.2 重置/覆盖
b.authors.set(a_list)

6. 正向查询： 查某本书的所有作者
主表对象.从表关联字段_.all()
b.authors.all()
############################################################
books = Book.objects.values('title',
        'publisher__name',   # 正向外键：外键字段__对应从表字段
        'authors__name',     # 正向多对多： 关联字段_对象从表字段
        'authors__email',
        )


############################################################

-- 反向添加 && 反向查找

反向查询: 关联主表表名小写__主表对应字段

从表对象.主表表名_set.all()
a.book_set.all()

# 反向查询，想拿主表相应字段信息，格式为<表名__主表属性字段名>如：book__title->book表的title字段属性
#查询内容是：出版社出版了哪些书
pub = Publisher.objects.values('name','city','book__title')

# 查询内容：查询作者出了哪些书？
author = Author.objects.values('name','email','book_title')

"""

learn/devops/hello/models.py
from django.db import models

class User(models.Model):       # 建立创建表当类
    SEX = (
        (0, '男'),
        (1, '女'),
    )
    name = models.CharField(max_length=10, help_text="用户名")
    password = models.CharField(max_length=5, help_text="密码")
    sex = models.IntegerField(choices=SEX, null=True, blank=True)       # 数据库0，1，展示男女

    def __str__(self):          # 当对象以字符串返回时，把name返回
        return self.name

learn/devops/books/views.py
from django.shortcuts import render

# Create your views here.

learn/devops/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse,QueryDict
from hello.models import User



# def index(request):
#     return HttpResponse("<p>Hello Django</p>")

# 2. 普通url带参数 http://ip:8000/?year=2021&month=04
# def index(request):
#     # 设置默认值获取数据更优雅
#     year = request.GET.get("year", "2021")
#     month = request.GET.get("month", "6")
#     return HttpResponse("year is %s,month is %s"% (year, month))

# 3.url通过识别关键字参数(?<参数名>参数类型)
# http://ip:8000/hello/2021/04
# def index(request, **kwargs):
#     print(kwargs)
#     year = kwargs.get('year')
#     month = kwargs.get('month')
#     return HttpResponse("year is %s,month is %s" % (year, month))

# 另一种写法--函数参数位置无关，以关键字为准备，更灵活
# def index(request, month, year):
#     return HttpResponse("year is %s,month is %s" % (year,month))

################ POST 请求传参 ################
# def index(request):
#     print(request.scheme)
#     print(request.method)
#     print(request.headers)
#     print(request.path)
#     print(request.META)
#     print(request.GET)
#     data = request.GET
#     year = data.get("year", "2021")
#     month = data.get("month", "04")
#     if request.method == "POST":
#         print(request.method)
#         print(request.body)
#         print(QueryDict(request.body).dict())
#         print(request.POST)
#         data = request.POST
#         year = data.get("year", "2021")
#         month = data.get("month", "04")
#     return HttpResponse("year is %s,month is %s" % (year,month))

# template渲染数据到html
def index(request):
    classname = "devops"
    books = ['python', 'java', 'Django']
    user = {'name':'dev','age':'30'}
    userlist = [{'name':'dev','age':'30'}, {'name':'rock', 'age':'29'}, {'name':'mage', 'age':'10'}]
    return render(request, 'hello/hello.html', \
                  {'classname': classname, "books":books, "user":user, "userlist":userlist})
    # return render(request, 'hello/hello.html')

# list user
def list(request):
    messages = ['1', '2', '3', '4', '5']
    value = ['python', 'django', 'java'] # python,django,java前端想这样展示
    # users = [
    #         {'username': 'dev', 'name_cn': 'dev', 'age': 18},
    #         {'username': 'dev1', 'name_cn': 'dev1', 'age': 19},
    #         {'username': 'dev2', 'name_cn': 'dev2', 'age': 20},
    #     ]
    users = User.objects.all()
    print(users)
    return render(request, 'hello/userlist1.html', {'users':users, 'messages':messages, 'value':value})

# def userlist(request):
#     users = User.objects.all()
#     return render(request, 'index.html', {'users':users})
def user(request):
    return render(request, 'hello/userlist1.html')

learn/devops/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deepsight Devops Platform</title>
</head>
<body>
<p style="background-color: chocolate;">
    {% block title %} 用户列表 {% endblock %}
</p>

<!-- 页面内容往往是变化的一块，做成变量即可 -->
{% block content %}

{% endblock %}

<!-- 每个页面都有哥底部且样式基本不会变，可以抽象出来 -->
<p style="background: beige;">版权所有：Deepsight Devops Platform 2020-2021</p>
</body>
</html>

learn/devops/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Devops</title>
</head>
<body>
<h1>Hello world</h1>


{% for key,error in forms.errors.items %}
    {{ error }}
{% endfor %}

<form action="" method="post">
<!-- form是UserForm的一个实例，通过render方法把它传递给模版。
as_table是form的一个方法，它把form渲染成表格行(as_ul和as_p也是起着相似的作用 )-->
    {{ form.as_p }}
    <input type="submit" value="提交">
</form>

</body>
</html>

learn/devops/templates/hello/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<br>
{# 第一个html页面#}
<p style="background-color: aquamarine;">hello Django</p>

{# 接受变量的值 #}
<p> {{ classname }}</p>

{# 接受列表中的值 #}
{#<li>{{ books.0 }}</li>#}
{#<li>{{ books.1 }}</li>#}
{#<li>{{ books.2 }}</li>#}
{# for循环接受列表的值 #}
{% for book in books %}
<li style="background: bisque";>{{ book }}</li>
{% endfor %}

{# 接受字典的中值 #}
<div style="background-color: blueviolet";>hello my name is {{ user.name }} </br>
my age is {{ user.age }}
</div>

{# for循环标签，渲染books列表#}
{% for user in userlist %}
<li style="background: cadetblue";>{{ user.name }}: {{ user.age }}</li>
{% endfor %}

{# if标签使用判断用户是否存在 #}
{% if user %}
    <p> name:{{ user.name }} </p>
{% else %}
    用户不存在
{% endif %}



</body>
</html>

learn/devops/templates/hello/modify.html
{% extends "base.html" %}

{% block title %} 用户更新 {% endblock %}

{% block content %}

{% if msg.code == 0 %}
    <p style="color: green">{{ msg.result }}</p>
{% else %}
    <p style="color: red">{{ msg.errmgs }}</p>
{% endif %}

<form method="post" action="" >
    姓名：
    <input type="text" name="name" value={{ user.name }}>
    <br>
    <br>
    密码：
    <input type="password" name="password" value={{ user.password }}>
    <br>
    <br>
    性别：
    {% if user.sex == 0 %}
        <input type="radio" name="sex" value="0" checked>男
        <input type="radio" name="sex" value="1">女
    {% else %}
        <input type="radio" name="sex" value="0">男
        <input type="radio" name="sex" value="1" checked>女
    {% endif %}
    <br>
    <br>
    <button type="sumbit" >确定</button>
    <button><a href="userlist.html">取消</a></button>
</form>

{% endblock %}

learn/devops/templates/hello/user_confirm_delete.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 用户删除 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}

<form action="" method="post">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="确定"/>
</form>

{% endblock %}

learn/devops/templates/hello/user_detail.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 个人信息 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}

<p> 姓名：{{ user.name }}</p>
<p> 密码：{{ user.password }}</p>
<p> 性别：{{ user.sex }}</p>

{% endblock %}

learn/devops/templates/hello/user_edit.html
{% extends "base.html" %}

{% block title %} 用户更新 {% endblock %}

{% block content %}

{% if msg.code == 0 %}
    <p style="color: green">{{ msg.result }}</p>
{% else %}
    <p style="color: red">{{ msg.errmgs }}</p>
{% endif %}

<form method="post" action="" >
    姓名：
    <input type="text" name="name" value={{ user.name }}>
    <br>
    <br>
    密码：
    <input type="password" name="password" value={{ user.password }}>
    <br>
    <br>
    性别：
    {% if user.sex == 0 %}
        <input type="radio" name="sex" value="0" checked>男
        <input type="radio" name="sex" value="1">女
    {% else %}
        <input type="radio" name="sex" value="0">男
        <input type="radio" name="sex" value="1" checked>女
    {% endif %}
    <br>
    <br>
    <button type="sumbit" >确定</button>
    <button><a href="userlist.html">取消</a></button>
</form>

{% endblock %}

learn/devops/templates/hello/user_form.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 创建用户 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}

{% if from %}
{#    <P style="color: red">{{ from }}</P>#}
    <P style="color: red">{{ from.errors }}</P>
    <P style="color: red">{{ from.name.errors }}</P>

{% endif %}


{% if messages %}
<ul>
    {% for messages in messages %}
    <li {% if messages.tags %} class="{{ messages.tags }}"{% endif %}>{{ messages }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="">
    <p>请输入用户名和密码</p>

    姓名：
    <input type="text" name="name">
    {% if form.name %}
    <p style="color: red">{{ form.name.errors }}</p>
    {% endif %}
    <br>
    <br>
    密码：
    <input type="password" name="password">
    <br>
    <br>
    性别：
    <input type="radio" name="sex" value="0" checked>男
    <input type="radio" name="sex" value="1">女
    <br>
    <br>
    <input type="submit" value="保存" name="_save">
    <input type="submit" value="保存并增加另一个" name="_addanother">
</form>
{% endblock %}

learn/devops/templates/hello/user_list.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 用户列表 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}
<!-- 搜索框 -->
<form action="{% url 'hello:userlist' %}">
    <input type="text" name="keyword" placeholder="请输入关键字">
    <button type="submit">搜索</button>
</form>

<!-- 数据表格 -->
<table border="1">
<thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>密码</th>
        <th>性别</th>
        <th>操作</th>
    </tr>
</thead>
<tbody>
<!-- 数据表格 -->
{% for user in users %}
<tr>
    <td>{{ user.id }}</td>
    <td>{{ user.name }}</td>
    <td>{{ user.password }}</td>
    <td>{% if user.sex == 0 %} 男 {% elif user.sex == 1 %} 女 {% else %} 未定义 {% endif %}</td>
    <td>
        <a href="{% url 'hello:modify' user.id %}">更新</a>
        <a href="{% url 'hello:userdel' user.id %}">删除</a>
    </td>
</tr>
{% endfor %}


</tbody>
</table>

{% endblock %}

learn/devops/templates/hello/useradd.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 添加用户 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}

{% if msg.code == 0 %}
    <p style="color: cadetblue"> {{ msg.result }} </p>
{% else %}
    <p style="color: red"> {{ msg.errmsg }} </p>
{% endif %}

<form method="post" action="">
    <p>请输入用户名和密码</p>
    <div>
    姓名：
    <input type="text" name="name">
    <br>
    <br>
    密码：
    <input type="password" name="password">
    <br>
    <br>
    性别：
    <input type="radio" id="selectSexf" name="sex" value="0" checked>
    <label for="selectSex" >男</label>
    <input type="radio" id="selectSexf" namne="sex" value="1">
    <label for="selectSexf" >女</label>
    <br>
    <br>
    </div>
    <div>
    <button type="submit" >确定</button>
    <button type="reset" >重置</button>
    </div>
</form>

{% endblock %}

learn/devops/templates/hello/userdel.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 用户删除 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}
{% if msg.code == 0 %}
    <p style="color: green"> {{ msg.result }} </p>
{% else %}
    <p style="color: red"> {{ msg.errmsg }} </p>
{% endif %}

<h1>确定要删除 {{ user.name }}?</h1>
<form method="post">
    <button type="submit">确定</button>
    <button><a href="{% url 'hello:userlist' %}">取消</a></button>
</form>

{% endblock %}

learn/devops/templates/hello/userlist.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 用户列表 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}
<!-- 搜索框 -->
<form action="{% url 'hello:userlist' %}">
    <input type="text" name="keyword" placeholder="请输入关键字">
    <button type="submit">搜索</button>
</form>

<!-- 数据表格 -->
<table border="1">
<thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>密码</th>
        <th>性别</th>
        <th>操作</th>
    </tr>
</thead>
<tbody>
<!-- 数据表格 -->
{% for user in users %}
<tr>
    <td>{{ user.id }}</td>
    <td>{{ user.name }}</td>
    <td>{{ user.password }}</td>
    <td>{% if user.sex == 0 %} 男 {% elif user.sex == 1 %} 女 {% else %} 未定义 {% endif %}</td>
    <td>
        <a href="{% url 'hello:modify' user.id %}">更新</a>
        <a href="{% url 'hello:userdel' user.id %}">删除</a>
    </td>
</tr>
{% endfor %}


</tbody>
</table>

{% endblock %}

learn/devops/templates/hello/userlist1.html
<!-- 继承母版不变的部分 -->
{% extends "base.html" %}

<!-- 重写母版变的部分 -->
{% block title %} 用户列表 {% endblock %}

<!-- 重写母版变的部分 -->
{% block content %}
<table border="2">
<thead>
    <tr>
        <th>用户名</th>
        <th>姓名</th>
        <th>年龄</th>
    </tr>
</thead>
<tbody>
    {% for user in users %}
    <tr>
        <td>{{ user.name }}</td>
        <td>{{ user.password }}</td>
        <td>{{ user.sex }}</td>
    </tr>
    {% endfor %}

</tbody>
</table>

<!-- Django过滤器，通过长度判断 -->
{% if messages|length >= 5 %}
    You have lots of messages today!
{% else %}
    You have not messages today!
{% endif %}

<br><br>
<!-- default---传入的值为false 则显示默认值"nothing"是默认值 过滤器 -->
{{ value|default:"nothing" }}

<!-- first/last----只展示列表中的第一/最后元素 -->
{{ value|first }}

<!-- join---将列表转为字符串，通python的 str.join(list) -->
{{ value|join:"," }} <!-- 如果value是列表['a', 'b', 'c'],输出字符串"a// b // c //" -->

<!-- slice: 切片。使用形式：{{ some_list | slice:":2" }} -->
 作用：与python语法中的slice相同，":2"表示第一的第二个元素
{{ some_list | slice:":1" }}

<br><br>
<!-- length---判断字符串和列表的长度 -->
{{ value|length }} <!-- 如果value是['a','b','c']或"abc"，输出将为3 -->
{{ value|length_is:"3" }} <!-- 如果value是['a','b','c']或"abc",则输出为True -->

<!-- static要链接保存在STATIC_ROOT中的静态文件，Django附带了static模版标记。无论是否使用RuquestContext，你都可以使用此方法。-->
{% load static %}
    <img src="{% static "images/01.jpg" %}" alt="Hi" />
{% load static %}

{% static "images/01.jpg"  as myphoto %}
    <img src="{{ myphoto }}"></img>

<!-- date: 如果value=datetime.datetime.now(),将返回当前时间的"年-月-日"格式 -->
{{ value|date:"Y-m-d" }}

<br><br>
{% load mytag %}
<p>{{ "2" |test:'1' }}</p>


{% endblock %}

learn/devops/templates/html-basic-knowledge.html
<!DOCTYPE html>
<!-- html标记语言基础知识 -->
<html lang="en">  <!-- html开始并且以/html结束，表示这是一个网页。html标签是成对出现 -->
<head>  <!-- 以head开始，并且以/head 结束这是网页头部信息段，-->
    <meta charset="UTF-8">
    <title>Title</title>
</head> <!-- 并且以/head结尾 -->
<body> <!-- body标签是网页段内容部门，也是成对出现 -->
<ul> <!-- ul:表示是列表的意思， -->
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
</ul>

<table border="2"> <!-- table:表示表单的意思 border="2" 表示给表单增加边框，并且边框的宽度为2 -->
<thead> <!-- thead：表示一个表的表头，内部是表头的字段内容-->
    <tr>
        <th>姓名</th> <!-- th：表示一个表的head头部，会进行加粗 表头字段使用th标签-->
        <th>性别</th>
        <th>年龄</th>
    </tr>
</thead>
<tbody> <!-- tbody:表示表的内容部门-->
    <tr> <!-- tr:表示表的行-->
        <td>john</td><td>男</td><td>35</td> <!-- td:表示表的列-->
    </tr>
    <tr> <!-- tr:表示表的行-->
        <td>john1</td><td>男</td><td>36</td> <!-- td:表示表的列-->
    </tr>
    <tr> <!-- tr:表示表的行-->
        <td>john2</td><td>男</td><td>37</td> <!-- td:表示表的列-->
    </tr>
</tbody>
</table>

</body>
</html>

learn/devops/templates/index.html
{% extends 'base.html' %}

{% block title %} 用户列表 {% endblock %}

{% block content %}

<table border="1">
<thead>
    <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>密码</th>
        <th>性别</th>
        <th>操作</th>
    </tr>
</thead>
<tbody>
{% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.password }}</td>
        <td>{{ user.get_sex_display }}</td>
{#        <td>{% if user.sex == 0 %}男 {% elif user.sex == 1  %}女{% else %}未定义{% endif %}</td>#}
        <td>
            <a href="{% url 'hello:modify' user.id %}">更新</a>
            <a href="{% url 'hello:userdel' user.id %}">删除</a>
        </td>
    </tr>
{% endfor %}
</tbody>
</table>

<br>
<form method="post" action="" >
    姓名:
    <input type="text" name="name" value="{{ object.name }}">
    <br>
    <br>
    密码:
    <input type="password" name="password" value="{{ object.password }}">
    <br>
    <br>
    性别:
    <input type="radio" name="sex" value="0" {% if object %}{% if object.sex == 0 %} checked {% endif %}{% endif %} >男
    <input type="radio" name="sex" value="1" {% if object %}{% if object.sex == 1 %} checked {% endif %} {% else %}checked{% endif %} >女
    <br>
    <br>
    <button type="submit" >确定</button>
    <button type="reset" >重置</button>
</form>
{% endblock %}

learn/devops/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deepsight</title>
</head>
<body>


<!-- 盒子模型标签 div-->
{#<div>#}
{#    <div><h1>python</h1></div>#}
{#    <div><h1>Django</h1></div>#}
{#</div>#}

<!-- 表格-->
{#<table border="1">#}
{#<thead>#}
{#    <tr>#}
{#        <th>姓名</th>#}
{#        <th>姓名</th>#}
{#    </tr>#}
{#</thead>#}
{#<tbody>#}
{#    <tr>#}
{#        <td>ds1</td><td>20</td>#}
{#    </tr>#}
{#    <tr>#}
{#        <td>ds2</td><td>21</td>#}
{#    </tr>#}
{#    <tr>#}
{#        <td>ds3</td><td>22</td>#}
{#    </tr>#}
{#</tbody>#}
{#</table>#}

<!-- form表单-->
<!-- {% url 'hello:html' %} 命名空间写法-->

{% if form %}
    {{ form.errors }}
{% endif %}

<form method="post" action="{% url 'hello:html' %}" enctype="multipart/form-data">
    <input type="hidden" name="ID" value="100">
    姓名：
    <input type="text" name="name" value="">
    <br>
    <br>
    手机：
    <input type="text" name="phone" value="">
    <br>
    <br>
    邮箱：
    <input type="text" name="email" value="">
    <br>
    <br>
    密码：
    <input type="password" name="password" value="">
    <br>
    <br>
    性别：
    <input type="radio" name="sex" value="0">男
    <input type="radio" name="sex" value="1">女
    <br>
    <br>
    爱好：
    <input type="checkbox" name="hobby" value="read">read
    <input type="checkbox" name="hobby" value="sport">sport
    <br>
    <br>
    技能：
{#        <select name="skill" size="3" multiple>#}
        <select name="skill">
            <option value="1" selected>Pyhton</option>
            <option value="2" >Java</option>
            <option value="3">PHP</option>
            <option value="4">JavaScript</option>
        </select>
    <br>
    <br>
    文件上传：
    <input type="file" name="file">
    <br>
    <br>
    个人简介：
        <textarea rows="3" cols="20" name="info" value="">
        </textarea>
    <br>
    <br>
    <input type="submit" name="save" value="确定">
    <input type="reset" name="reset" value="重置">
</form>


</body>
<!-- 超链接标签-->
<a href="http://www.baidu.com" target="blank">点击我，会跳转</a>
<footer style="background: cadetblue">Deepsight Devops Platfrom </footer>
</html>